### PR TITLE
feat: Implement #44 and #49

### PR DESCRIPTION
**Pull request by NightFeather0615**
Hello! I've implemented the features mentioned in #44 and #49, by the way, I'm not sure if the SVG's height should stay or shrink when activity section is hidden.

Please let me know if there is a cleaner way to implement #44, I think it's a bit messy 😓.

### CODE REVIEW

**Comment by cnrad** [comment]
need to figure out how to update node without it breaking, will merge once I test but looks good overall

**Comment by cnrad** [comment]
Hey, could you sync your branch with the two new commits to this repo so I can authorize a deployment on Vercel and test things out? Thanks

**Comment by NightFeather0615** [comment]
Sure! I've synced the branch to latest commit and everything seems fine, should be ready to deploy.

**Comment by cnrad** [comment]
lgtm, thanks for the contribution :)

**Pull request merged**
