### PR TITLE
HUGE PR: return boolean expression instead of using if statement

### PR DESCRIPTION
**Pull request by Hexiro**
before this was an if statement. now it is a boolean expression. 😊😊😊😊😊😊😊😊😊

### CODE REVIEW

**Comment by Looskie** [comment]
LETS GOOOO

**Comment by Hexiro** [comment]
> LETS GOOOO

👉🏼 👶🏼 👈🏼

**Comment by cnrad** [comment]
I didn't even make the snowflake validation thing but lgtm so thanks

**Comment by alii** [comment]
Big pr. Thanks nathf

**Comment by Looskie** [comment]
Big pr. Thanks nathf

**Comment by Hexiro** [comment]
welc

**Pull request merged**
